### ISSUE TITLE
Using function pointers with itype

### ISSUE THREAD

**Issue by 2000jedi** [microsoft/checkedc-clang#1027]
I would like to pass a function pointer as a parameter to a function, but when I try to use an itype for the function pointer, the compiler fails.

    _Checked void cp(
      void (*copy)(
        char* buf : itype(_Array_ptr<char>) count(len),
        int len
      ) : itype(_Ptr<void(_Array_ptr<char> buf : count(len), int len)>)) {}

The Checked C compiler shows the following error:
> interface type only allowed for a pointer return type

Is there any way to modify this code to make it work?
i.e. `cp()` could take in both a raw function ptr and a checked function ptr?

**Comment by mattmccutchen-cci** [comment]
I'm a 3C developer (not a Checked C maintainer), but I ran across this issue and I think I know the answer, so I'm posting it.  You need an extra set of parentheses around the function pointer name and parameter list:
```c
_Checked void cp(
  void ((*copy)(
    char* buf : itype(_Array_ptr<char>) count(len),
    int len
  )) : itype(_Ptr<void(_Array_ptr<char> buf : count(len), int len)>)) {}
```
See [`bsearch` in the Checked C system headers](https://github.com/microsoft/checkedc/blob/f3af449e8b7c18556faabd4a48da928cf8c0d572/include/stdlib_checked.h#L90-L95) for an example.

This should probably be documented better.
