### ISSUE TITLE
`_Nt_array_ptr` sometimes widened without checking if the element was non-null (unsound)

### ISSUE THREAD

**Issue by mattmccutchen-cci** [microsoft/checkedc-clang#1073]
The following code compiles with no warnings but generates a segmentation fault at runtime:
```c
#pragma CHECKED_SCOPE on

int main(void) {
  char arr _Nt_checked[10];
  unsigned int i = 0;
  _Nt_array_ptr<char> p : count(i) =
    _Dynamic_bounds_cast<_Nt_array_ptr<char>>(arr, count(i));
  for (;;) {
    char x = p[i];
    i++;
  }
  return 0;
}
```
I'm not sure exactly where the compiler is going wrong here.  It seems that the compiler is allowing the bound for `p` to be automatically widened even though the code does not check that `p[i] != '\0'`.  The problem doesn't occur if the type of `i` is changed to `int`, so there may be some strange interaction going on here.

**Comment by kkjeer** [comment]
This issue was due to a bug in the `CreateStandardForm` method, where the compiler allowed the inferred bounds `bounds(p, p + i - 1)` to imply the bounds `bounds(p, p + i)` for an `_Nt_array_ptr<char>` `p`. This is fixed by #1087.
