### ISSUE TITLE
Compiler issues in Apple Silicon Systems

### ISSUE THREAD

**Issue by Vedaant-Rajoo** [microsoft/checkedc-clang#1195]
While building the CheckedC compiler on my system, I came across this error while compiling checkedC code
<img width="783" alt="Screen Shot 2022-01-17 at 1 45 30 PM" src="https://user-images.githubusercontent.com/33187221/149823658-3b9982d6-e83d-4d05-8d79-723d571e00cc.png">
.
I made the build files with everything according to the wiki provided.
1. My target was `ARM` architecture processors.
2. Added sysroot location while building.

Can anyone point out what I'm doing wrong and suggest a fix?

**Comment by sulekhark** [comment]
No active development is happening on the checkedc-clang compiler in this repository. Please file your issue here: https://github.com/secure-sw-dev/checkedc-llvm-project. This is the new home of the checkedc-clang compiler.
