### ISSUE TITLE
Test use of `_Dynamic_check` when Checked C not enabled

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#123]
If a programmer doesn't have Checked C enabled (using `-fcheckedc-extension`), we need to make sure that if they have a function called `void _Dynamic_check(int)` that they can call it, and our extension doesn't get in the way. This may entail changing `_Dynamic_check` to become a LANGBUILTIN.

**Comment by dtarditi** [comment]
I remember that functions being with _ and a capital letter are "reserved for the system".   So we don't have to worry about this unless we run into a library that is using _Dynamic_check.   We will not do this work item.
