### ISSUE TITLE
Add Dynamic Bounds Checks at all reads of Checked Arrays

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#147]
Specifically inserting dynamic bounds checks at all places where a `checked[]` array is read, `e[e1]`, `*e`, and all lvalue reads. 

This should be quicker, as most of the code will be in place from #145 and #146. Instead of taking two weeks, it should take less than half a week.

**Comment by dtarditi** [comment]
We actually ended up putting the dynamic checks on lvalue expressions that are then used in assignment or read (PR #171).  This subsumed this work item.
