### ISSUE TITLE
Add Dynamic Checks to Checked Pointer Assignment Operations

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#149]
#145, #146, #147, and #148 only relate to reading checked pointer types. 

We need to do the same checks every time an expression containing a checked pointer appears on the left of an assignment operator.

**Comment by dtarditi** [comment]
We actually ended up putting the dynamic checks on lvalue expressions that are derived from array_ptr types and are used as the LHS of an assignment or the in a read from memory (LValueToRValue cast).   This work item is now complete.
