### ISSUE TITLE
Add Dynamic Checks on Inc/Decrement and Compound Assignment Expressions

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#150]
This is a version of #149 for (post-/pre-) inc/decrement expressions such as `++e`, as well as compound assignment expressions (such as `e += e2`) containing checked pointer types.

**Comment by dtarditi** [comment]
We actually ending up putting the dynamic checks on lvalue expressions that are used in increment/decrement expressions and as the lhs of compound assignment expressions.    This work items then became to write tests that this worked as expected.  This work was completed by pull requests #183 and #185.
