### ISSUE TITLE
Add Bounds Inferred Bounds Information to AST

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#151]
One problem we have with implementing bounds checks is that the inferred bounds information (acquired during semantic analysis) is not available to code generation.

We're going to start explicitly keeping bounds information around in the AST so that it can be used in code generation.

I believe we only need to keep it around for the following expression types:
- UnaryOpExpr (for Derefs, Increments and Decrements)
- AssignmentExpr
- CompoundAssignmentExpr
- ArraySubscriptExpr

which should lessen the overhead of this addition significantly. 

This needs to update:
- [ ] Expr Class Definitions (including getters and setters)
- [ ] AST (De)Serialization
- [ ] AST Dumping
- [ ] Getters/Setters

**Comment by dtarditi** [comment]
This was addressed by pull request #153.  We only need to record inferred bounds information in a few places where lvalues are used to access memory:
- Casts (for lvalue-to-rvalue casts)
- Member reference expressions, 
- At assignments (for the LHS)
- For unary increment and decrement operators.
