### ISSUE TITLE
Insert bitcasts when necessary for arguments passed to itype Parameters

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#159]
At the moment we're about to merge #157, which corrects the assertion within Clang Code generation.

This is not the right long-term fix, but will get us making progress again. A better fix is to insert a Bitcast around the parameter to change from the itype-type to the declared type. This seems to be a fairly involved change.

[I have a branch here](https://github.com/Microsoft/checkedc-clang/compare/master...lenary:itype_call_mismatch_codegen) for a first attempt at the change, but this is not a good long-term change either, I think we need to add an "initialization step", which would then be processed in `InitializationSequence::Perform` in `SemaInit.cpp`

**Comment by dtarditi** [comment]
This was fixed by PR #367.
