### ISSUE TITLE
Add checked scope

### ISSUE THREAD

**Issue by wonsubkim** [Microsoft/checkedc-clang#189]
add checked scope
checked scope is program scope for checked pointer type (refer to ch 2.7)
we will implement first checked scope not unchecked scope

checked scope syntax
1. **checked** _compound_stmt_ ({... })
2. **checked** _function_declaration_

In checked scope, it is allowed to have checked pointer types, checked array types or unchecked pointer types, unchecked array types with bounds-safe interface

**Comment by wonsubkim** [comment]
Requirement

- In checked scope, code is limited to use pointer types that are checked pointer types or unchecked pointer types with bounds-safe interface

-  In checked function, function declaration can have use checked pointer types for return type and function parameter types

- In checked function, function body is defined as checked scope by default

- In checked scope, function without prototype is not allowed to use

**Comment by wonsubkim** [comment]
In checked function, checked keyword acts as new function specifier
checked function specifier is added in Declarator and it enforces to check if
function declarator has proper type or function definitions has proper statement type

In checked scope, checked keyword insert additional property into related scope
checked property is added Scope/CompoundScope

According to this checked property, Sema (Semantic) will check if 
declaration statement has proper checked pointer type
or function declarator has proper return/parameter type

**Comment by dtarditi** [comment]
I have created work items for this feature: issue #199, issue #200, issue #201, and issue #202.

**Comment by wonsubkim** [comment]
I have a question about work item management

The new created work items have different status in my thought
Some work items such as #199, #200 are related to current PR (#193)
I am now working on parsing of checked scope and declaration type restriction in #193 PR
and testing those with simple test code in checkedc
So, if #193 PR is completed, those two work items can be closed

Other work items such as #201, #202 are not yet implemented but works to do
How about your idea?

**Comment by wonsubkim** [comment]
Related issues (#199, #200, #201, #202, #247, #251)

**Comment by dtarditi** [comment]
The feature is complete.
