### ISSUE TITLE
Implement parsing for checked scopes

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#199]

**Comment by wonsubkim** [comment]
### checked function
- syntax: **checked** _function_declaration_
- parsed as **function specifier**
- checked function specifier affects function declaration (return & parameter type) and function body (checked compound statements)
- Also checked function restricts function without a prototype
- ex) `checked void func(int len, int *start, int *end) {... }`
``
### checked block/scope
- syntax : **checked** { }
- checked property is propagated into scope/compound scope
- ex) `int sum(int a, int b) checked { ... }` // checked keyword is located before l_brace
- ex) `struct a checked { ... }` // checked keyword is located before l_brace

**Comment by wonsubkim** [comment]
This work item is related to PR (#193)

**Comment by dtarditi** [comment]
I believe this work is complete, so I'm closing this item.
