### ISSUE TITLE
Implement type restrictions on declarations in checked blocks.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#200]
They are not allowed to use unchecked pointer types.

**Comment by wonsubkim** [comment]
This work item is related to PR (#193)
For initial version of type checking, I have implemented type restriction on declarations in checked blocks

**Comment by wonsubkim** [comment]
To consider interop-type for globally-scope variable & parameter, I think that type restrictions on declaration is slightly changed.
By implementing & testing checked top-level scope, I have found some problems for this
I will fix up it in related issue (#246, #247)

**Comment by wonsubkim** [comment]
For constructed type checking, we have added constraints as follows:
- checked pointer to unchecked pointer is not allowed in checked (No declaration)
- variable arguments type is not allowed in checked block (No declaration)

**Comment by dtarditi** [comment]
This work is complete.
