### ISSUE TITLE
Implement restrictions on types in expressions in checked blocks.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#202]
- No uses of variables or members that have unchecked pointer type and no bounds-safe interface.
- No C-style casts to unchecked pointer type.

**Comment by wonsubkim** [comment]
when parsing expression statement, check if each element is unchecked type or not in checked scope
Also, unchecked pointer type casting is not allowed in checked scope

**Comment by wonsubkim** [comment]
For constructed type checking, we have added constraints as follows:
- checked pointer to unchecked pointer is not allowed in checked (No use, No C-style type cast)
- variable arguments type is not allowed in checked block (No use, No C-style type cast)

**Comment by dtarditi** [comment]
This work is complete.
