### ISSUE TITLE
Allow Checked C Convert to convert to `ptr<T>`

### ISSUE THREAD

**Issue by lenary** [microsoft/checkedc-clang#229]
There should be an option in for the converter to use `ptr<T>` instead of `_Ptr<T>`, where people are using the correct headers. 

An option like `--no-underscore-types` or similar. There's no need for the converter to insert the header, and there should remain the ability to insert `_Ptr<T>` types, as some people will need that too.

**Comment by awruef** [comment]
I like this idea. It shouldn't be too hard.

**Comment by lenary** [comment]
I guess in general this applies to all keywords, it's just you only introduce `ptr<T>` for the moment.

**Comment by mgrang** [comment]
Issue filed with 3C: https://github.com/correctcomputation/checkedc-clang/issues/417
