### ISSUE TITLE
Internal compiler assert in SemaBounds.cpp

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#231]
I have been enabling LNT testing and found that MultiSource/Benchmarks/McCat/09-vor is failing with an internal compiler error in SemaBounds.cpp.

The problem is that we were assuming that all base expressions of structures are lvalues.  According to the C specification, they do not have to be lvalues.   For example, a call can produce a structure value that is not an lvalue.

**Comment by lenary** [comment]
Closed by #232
