### ISSUE TITLE
Checked C Converter Doesn't Convert as Much as Expected

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#241]
in Microsoft/checkedc-llvm-test-suite#21, I pointed out that only one or two pointers were changed by checked-c-converter rather than by manual changes (look at the diff, there are two comments, both were pointers to the `Hospital` struct)

I wasn't sure if it was an issue with the headers or something.

Steps to reproduce (sorry, this is quite a long list):
- Install lnt (into a virtualenv) and clone the checkedc-llvm-test-suite. For me, lnt ends up in `./llvm.lnt.ve/bin/lnt` and the test suite ends up in `./checkedc-llvm-test-suite`. I'm assuming you already have a clang build dir at `./llvm.build/bin/clang`. 
- Check out checkedc-llvm-test-suite to `f82c1b933a55194c777318a2d3eb3708baa291a0` (the commit before my manual conversion was merged).
- Run the following at the shell. This will output a lot of information. You can ignore most of it. Change the locations in the first 3 lines if yours are different. This command is run from the directory *above* the directory you have `checkedc-llvm-test-suite` in, not from within the repo. It doesn't matter where the sandbox goes (4th line), it will be created for you. Don't change the `--only-test` line, it's relative to the test suite, not relative to where the command was run from. 
```
./llvm.lnt.ve/bin/lnt runtest test_suite \
  --cc ./llvm.build/bin/clang \
  --test-suite ./checkedc-llvm-test-suite \
  --sandbox ./llvm.lnt.sandbox \
  --cflags -fcheckedc-extension \
  --cmake-define "TEST_SUITE_TAKE_COMPILE_TIME=OFF" \
  --cmake-define "CMAKE_EXPORT_COMPILE_COMMANDS=ON" \
  --only-test MultiSource/Benchmarks/Olden/health \
  --no-timestamp
```
- Copy `./llvm.lnt.sandbox/build/compile_commands.json` into `./checkedc-llvm-test-suite`
- cd into `checkedc-llvm-test-suite`
- Run `checked-c-convert -output-postfix=checked MultiSource/Benchmarks/Olden/health/*.c`
- Diff the `MultiSource/Benchmarks/Olden/health/*.c` files against the new `MultiSource/Benchmarks/Olden/health/*.checked.c`

What you will see:
- Only two or so pointers changed.

What you should see:
- More pointers changed than that. I'd hope.

**Comment by awruef** [comment]
Interesting, I'll look into this.

**Comment by awruef** [comment]
Looking at the `health` benchmark, I bet one reason this happens is because of pollution due to casts from `malloc`. Right now there isn't a good story for casts in the re-writer. I'll think some about a strategy for this, it seems important.

**Comment by dtarditi** [comment]
Stale item.
