### ISSUE TITLE
Duplicate Errors on assignment of *T expression to ptr<T> variable

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#242]
When converting some benchmarks, I got the following duplicated error messages, in every place where I was assigning something of type `*T` into a `ptr<T>` typed variable. 

In this particular case, `localnode->from_values[i]` has type `*double` and `other_value` has type `ptr<double>`
```
/Users/ashe2/Code/checkedc-llvm-test-suite/MultiSource/Benchmarks/Olden/em3d/em3d.c:27:21: error: expression has no
      bounds, right-hand side of assignment expected to have bounds because the left-hand side has bounds
      other_value = localnode->from_values[i];
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ashe2/Code/checkedc-llvm-test-suite/MultiSource/Benchmarks/Olden/em3d/em3d.c:27:21: error: expression has no
      bounds, cast to ptr<T> expects source to have bounds
      other_value = localnode->from_values[i];
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
```

We should definitely only be emitting one of these errors, not both. I think perhaps the second one is closer to the "truth" (or a truth that reveals the fix), but we should probably be aiming for something like "expression of type `*T` cannot be cast to `ptr<T>` implicitly". I'm not sure even mentioning bounds here is useful, as `ptr<T>`s don't have the same notion of bounds that `array_ptr<T>` has.

**Comment by lenary** [comment]
Follow-up:

Attempting an explicit cast shows how these errors are slightly different. I maintain having both is not useful, and I think an explicit cast should get rid of both. My understanding is that explicit casts would not be checked except if you used the special new casts we were introducing. 

```
/Users/ashe2/Code/checkedc-llvm-test-suite/MultiSource/Benchmarks/Olden/em3d/em3d.c:27:21: error: expression has no
      bounds, right-hand side of assignment expected to have bounds because the left-hand side has bounds
      other_value = (_Ptr<double>)localnode->from_values[i];
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ashe2/Code/checkedc-llvm-test-suite/MultiSource/Benchmarks/Olden/em3d/em3d.c:27:35: error: expression has no
      bounds, cast to ptr<T> expects source to have bounds
      other_value = (_Ptr<double>)localnode->from_values[i];
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dtarditi** [comment]
This is fixed.
