### ISSUE TITLE
Checked C Converter Drops `register` qualifiers

### ISSUE THREAD

**Issue by lenary** [microsoft/checkedc-clang#243]
I have some code where checked-c-convert starts with:
```
register double *other_value;
```

and converts this to:
```
_Ptr<double> other_value;
```

The code can be seen here: https://github.com/Microsoft/checkedc-llvm-test-suite/pull/23/commits/e432fb16c845b826e95968fb3cc57e290b80f3c8?diff=unified#diff-235a34864cf9f3202660ee2eef8c98f2R15

Is it intended that the converter drops the `register` storage qualifier?

**Comment by awruef** [comment]
It isn't intended but it's not unexpected. In the rewriter we have to mirror all of the different qualifiers that a type could have, and `register` is not one that we handle right now. It is a small change to add it though.

**Comment by mgrang** [comment]
Issue filed with 3C: https://github.com/correctcomputation/checkedc-clang/issues/416
