### ISSUE TITLE
Implement BOUNDS_CHECKED pragma

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#247]
This allows us to make the top-level scope of a compilation unit checked.

**Comment by wonsubkim** [comment]
#pragma BOUNDS_CHECKED on/off/default
If value is on, top level scope of compilation unit is defined as checked scope
If value is off or default, top level scope is defined as unchecked scope.

I think that by default top level scope is unchecked scope. Therefore, value off is same as value default

Is there any different between default and off?

**Comment by dtarditi** [comment]
Yes, it makes sense for the default state to be "off".   Could you update the spec in the Checked C repo to describe this?

**Comment by wonsubkim** [comment]
Yes, I can

**Comment by dtarditi** [comment]
This work is complete.
