### ISSUE TITLE
Do not allow calls to variable argument functions in checked blocks

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#251]
We currently have no way to enforce that arguments with correct types are passed to variable argument functions such as printf.   For now, we should not allow calls to variable argument functions in checked blocks.

**Comment by wonsubkim** [comment]
In checked blocks, a variable argument function call is not allowed.
How about a variable argument function declaration?
A variable argument function declaration SHOULD be prohibited?
A variable argument standard library function prototype SHOULD be prohibited if #pragma BOUNDS_CHECKED on ?

**Comment by wonsubkim** [comment]
I am little bit confused that variable argument function is prohibited in checked blocks.
For a variable arguments, what is correct type of argument?

In checked blocks, only checked type argument can be used as actual argument.
If function expects a checked pointer type, it is not a problem.
Although function expects an unchecked pointer type, I think that it is not problem if actual argument is a checked type.

**Comment by dtarditi** [comment]
This work is complete.
