### ISSUE TITLE
typedef error messages desugar incorrectly

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#254]
If you have a typedef used in a written type, which desugars to a `ptr<T>` or `array_ptr<T>` type, when the error printer desugars the typedef type, it prints it as `T *`, which can be confusing.

Here is a not-very-confusing example: 
```
/Users/ashe2/Code/checkedc-llvm-test-suite/MultiSource/Benchmarks/Olden/em3d/make_graph.c:357:19: error: assigning to
      '_Array_ptr<_Ptr<node_t>>' (aka 'struct node_t **') from incompatible type 'table_arr_t'
      (aka 'struct table_arr_t')
```

However, I've seen examples where I've tried assigning into a `ptr<T>` from a `T *` and you get an error message that says `error: assigning to '_Array_ptr<Node>' (aka 'struct node_t *') from incompatible type 'Node *' (aka 'struct node_t **')` which is a lot more confusing.

**Comment by dtarditi** [comment]
This is fixed.
