### ISSUE TITLE
Address-of Operator, Checked Blocks, and Function Pointers

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#272]
Recently we changed the semantics of `&` (address-of) in checked blocks to return an `array_ptr<T>` rather than a `ptr<T>`, to avoid narrowing. This mostly makes sense.

However, we need to be careful with function pointers. If we have a function declared at the top level, say `int id_int(int x) { return x }`, then `id_int` has "function type" `int(int)`, and `&id_int` has function pointer type, `int(*)(int)`. We are careful in Checked C to disallow checked array pointers to functions, because we don't want people indexing into them. So, for instance, `ptr<int(int)>` is a valid type, but `array_ptr<int(int)>` is not, and cannot be constructed.

This, therefore gives us a problem. `&id_int` within a checked block, if we follow the new rules for `&`, will have type `array_ptr<int(int)>` which cannot be constructed, giving an error. But we do want to allow statements like `ptr<int(int)> fn = &id_int`. 

This suggests that for address-of expressions `&e` inside a checked block, if `e` is a function pointer, then `&e` should have checked function pointer type, `ptr<T>`, otherwise `&e` should have `array_ptr<T>` type. 

There is the second problem of Implicit `FunctionToPointerDecay` Casts, (in the C11 spec, Section 6.3.2.1 Paragraph 4). It is valid to also write `ptr<int(int)> fn = id_int`, and clang will insert this implicit function to pointer decay, which does the equivalent of the `&` operator. 

Changing `&` suggests we should also make sure this Function To Pointer Decay to returns a `ptr<T(T...)>`. This should correspond to making sure that all pointers in a checked block are checked pointers.

**Comment by wonsubkim** [comment]
Okay. I think that it is correct.
I will apply this issue. Thanks

**Comment by wonsubkim** [comment]
```
int id_int(int x) { return 0; }
ptr<int> id_checked_intp(ptr<int> x) { return 0; }
```
In previous implementation, implicit conversion from array_ptr<T> to ptr<T> in function pointer
```
extern void test checked {
   ptr<int(int)> fn0 = id_int; // ImplicitCast ptr {FunctionToPointerDecay}
   ptr<int(int)> fn1 = &id_int; // ImplicitCast ptr {UnaryOperator &}

   ptr<ptr<int>(ptr<int>)> fn8 = id_checked_intp; // ImplicitCast ptr<> {FunctionToPointerDecay}
   ptr<ptr<int>(ptr<int>)> fn9 = &id_checked_intp; // ImplicitCast ptr<> {UnaryOperator &}
}
```
In current implemention, address-of (&) operator will generate ptr<FunctionType>
FunctionToPointerDecay implicit casting also will generate ptr<FunctionType>
```
extern void test checked {
   ptr<int(int)> fn0 = id_int; // FunctionToPointerDecay ptr<int(int)>
   ptr<int(int)> fn1 = &id_int; // & produces ptr<int(int)>

   ptr<ptr<int>(ptr<int>)> fn8 = id_checked_intp; // FunctionToPointerDecay ptr<FT>
   ptr<ptr<int>(ptr<int>)> fn9 = &id_checked_intp; // & produces ptr<FT>
}
```

**Comment by dtarditi** [comment]
This work is complete.
