### ISSUE TITLE
Do not allow some bounds_cast operations in checked scope

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#277]
Once the work on _Assume_bounds_cast is finished, we need to make sure it cannot be used in a checked scope.

**Comment by wonsubkim** [comment]
Prevent _Assume_bounds_cast ?
Prevent _Assume_bounds_cast / _Dynamic_bounds_cast to unchecked type?

**Comment by dtarditi** [comment]
We want to prevent all _Assume_bounds_cast in a checked scope.   They could be wrong even for checked pointer to checked pointer casts.

You are correct that we should also prevent _Dynamic_bounds_cast to unchecked types.

**Comment by wonsubkim** [comment]
As soon as bounds_cast issue finished, I will apply this issue

**Comment by dtarditi** [comment]
This work is complete.  Thank you!
