### ISSUE TITLE
Check types of operands of *_bounds_cast operators

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#286]
This should be done separately from PR #269.  The first operand must be suitable for casting to a pointer type: it must be a pointer type or an integral type.    If there is only a second operand, it must have a type suitable for a count expression.  If there are second and third operands, they must have types suitable for a bounds expression.

We might want to change the syntax of dynamic_bounds_cast and assume_bounds_cast to take an actual bounds expression as the second argument:
```
array_ptr<int> x : count(10) = dynamic_bounds_cast<array_ptr<int>>(x, count(10));
array_ptr<int> x : bounds(a, b) = dynamic_bounds_cast<array_ptr<int>>(x, bounds(a, b));
```

**Comment by jijoongmoon** [comment]
I think it is only needed to check first operand if it is pointer type or integral type. The check about second operand and third operand, the type checking are done in ActOnCountBoundsExpr and ActOnRangeBoundsExpr. In ActOnCountBoundsExpr, isIntegerType() is done for the E2 and ValidateBoundsExprArgument(E2) and ValidateBoundsExprArgument(E3) are done in ActOnRangeBoundsExpr. If we are doing these check during the parsing bounds cast expression, I think it is duplicated. Am I right?

**Comment by dtarditi** [comment]
I agree that we only need to check the first operand.

Yes, it is OK to use the relative clause for the bounds as below.

**Comment by dtarditi** [comment]
This work is complete - thanks Jijoong!
