### ISSUE TITLE
When re-writer works with casts, cast to checked types

### ISSUE THREAD

**Issue by awruef** [microsoft/checkedc-clang#294]
Right now, the re-writer won't change casts to be casts to checked types. One reason for this is that the `mkString` method in the `ConstraintVariable` infrastructure produces a string that both has the variable and the type declaration in it. To support this feature, a `mkTypeString` method should be added that takes a given set of constraints and base type and produces a string that is just the type. Then, the `CastPlacementVisitor` can be updates to handle additional cases (`VisitBinAssign`, `VisitDeclStmt`, etc) where casts might be present and replace the body of the cast.

**Comment by dtarditi** [comment]
Closing this issue as stale.  The convert tool has been mostly rewritten (see PR #642).
