### ISSUE TITLE
Odd Rewriter Bug

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#297]
I decided to re-run the rewriter on the benchmarks (from the test suite), to see if they converted more pointers than before.

In (https://github.com/Microsoft/checkedc-llvm-test-suite/blob/pre-conversion-benchmarks/MultiSource/Benchmarks/Ptrdist/anagram/anagram.c)[`anagram.c`] the converter does something odd:

The function `FindAnagram()` starts as:
```c
void
FindAnagram(Quad * pqMask, PPWord ppwStart, int iLetter)
{
    Quad aqNext[MAX_QUADS];
    register PWord pw;
    Quad qMask;
    unsigned iq;
    PPWord ppwEnd = &apwCand[0];
```

And is converted to:
```c
void
FindAnagram(Quad * pqMask, Word*_Ptr<Word>  ppwStart, int iLetter)
{
    Quad aqNext[MAX_QUADS];
    _Ptr<Word>  pw;
    Quad qMask;
    unsigned iq;
    Word*_Ptr<Word>  ppwEnd = &apwCand[0];
```

In particular, the thing i find odd is the `Word*_Ptr<Word>` type name. That doesn't seem valid. 

I'm using the same build instructions as in #241, only the compile_commands.json was generated from an LNT test that didn't have the `--only-test ...` specifier, so I could apply it to all the benchmarks.

**Comment by awruef** [comment]
I guess it should be `_Ptr<Word> *ppwEnd`, I have an idea why that happens.

**Comment by awruef** [comment]
Well, the good news is that after the most recent changes in the awruef:awr_25 branch, this doesn't happen any more. The bad news is that we go back to promoting not that many pointers.

**Comment by dtarditi** [comment]
This has been fixed, so closing this issue.
