### ISSUE TITLE
Bounds checks are using signed integer compares.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#298]
The lowering of bounds checks to LLVM IR is using signed integer comparison for pointer comparisons.  It should use unsigned integer comparison instead.

**Comment by lenary** [comment]
I wonder what that merged pull request does to performance. I'll kick off another benchmark run this afternoon.

**Comment by lenary** [comment]
The answer to my question is "yes", with almost universal improvement in comparative run time in our preliminary benchmarks. 

This issues is fixed by the PR, so I'll close it.
