### ISSUE TITLE
Revisit function to pointer type decay in a checked scope

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#304]
PR #303 changes implicit casts for function-to-pointer type decay to always produce an unchecked pointer type.   In a checked scope, it should produce a checked pointer type.   This work item is to revisit the change in PR #303 for implicit casts for function-to-pointer decay.

The rationale is given in the pull request for the checked repo test code:

> When generating function call in checked scope, I have generated implicit cast expression for checked pointer type for FunctionToPointerDecay
> In function declaration having KNR parameters, it has empty parameter types
> For function call for KNR function , SemaBounds generates implicit casting expression from incompatible type.
> For call expression, DO NOT generate checked pointer type of function

We should not be allowing calls to no-prototype functions in checked scopes.  I think a function having a K&R parameter list should end up as no-prototype function.   m not sure 100% sure what is going on here: whether this is call to a no-prototype function or whether clang sees the K&R definition and constructs a prototype for it that it can be used for subsequent calls.

**Comment by wonsubkim** [comment]
According to current observation, function having KNR parameter list is similar to no-prototype function when it is called. In AST dump, function call to KNR parameter function seems to be no-prototype function prototype.
Do you think that this type of function (KNR parameter function) SHOULD be prevented in checked scope?
Also KNR parameter function declaration SHOULD be disabled?

**Comment by wonsubkim** [comment]
In function call, KNR parameter function call is generated as DeclRefExpr having FunctionNoPrototype
Function declaration has its proper type but when building DeclRef expression, it generates NoPrototypeFunction type.
I think that we SHOULD check if it is in checked scope

**Comment by dtarditi** [comment]
Yes, I think calls to functions without prototypes should be disabled in checked scopes.  In addition, declarations of functions without prototypes should be disabled in checked scopes.   Do you agree?

**Comment by wonsubkim** [comment]
A normal no-prototype function declaration & use is already disabled in checked scope
However, this situation is slightly exceptional
KNR paramter function is not no-prototype function declaration but normal function declaration because actually it has proper function parameters
But, when building DeclRefExpr (at function call), it creates no-prototype function type DeclRefExpr for function call to KNR parameter function
Therefore, I will prevent function call of this type

**Comment by dtarditi** [comment]
This work is complete.
