### ISSUE TITLE
Bounds error produced before typechecking error

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#305]
In the new test case tests/CheckedC/type-checking-crash.cpp, a bound error message is emitted before a type checking error.  The type checking error causes the bounds error message, so it should go first (under the theory programmers will try to fix the first error message they see.  This work item is to understand why the bounds error message is being emitted first and fix this if possible.

**Comment by jp1729** [comment]
Here are the observations I made in regards to the behavior of error messages:
```
type-checking-crash.c:26:4: error: member reference type 'struct S' is not a pointer; did you mean to use '.'?
  s->arr[i] = 1; 
  ~^~
   .
type-checking-crash.c:26:3: error: expression has no bounds
```

The error message is emitted in the correct order. 
The interesting insight is that clang -verify does not care about the order of the emitted message, contrary to FileCheck. Therefore, the two tests below will both pass:
```
s->arr[i] = 1; //expected-error{{member reference type 'struct S' is not a pointer; did you mean to use '.'?}} //expected-error{{expression has no bounds}}
```
```
s->arr[i] = 1; //expected-error{{expression has no bounds}} //expected-error{{member reference type 'struct S' is not a pointer; did you mean to use '.'?}}
```

I am not aware of a method to test for order of emitted error messages that is compatible with llvm-lit.py.

**Comment by dtarditi** [comment]
Thanks for looking into this!   I was not aware that the verify method did not care about the order of error messages for a line.  The behavior makes sense.
