### ISSUE TITLE
Casting to _Ptr<void> in free.

### ISSUE THREAD

**Issue by lenary** [Microsoft/checkedc-clang#318]
This error is coming up frequently:

```
/path/to/checkedc-llvm-test-suite/MultiSource/Benchmarks/Ptrdist/yacr2/assign.c:68:7: error: passing
      '_Array_ptr<long>' to parameter of incompatible type 'void *'
        free(costMatrix[net]);
             ^~~~~~~~~~~~~~~
/path/to/bin/../lib/clang/4.0.0/include/stdlib_checked.h:54:17: note: passing argument to parameter
      'pointer' here
void free(void *pointer : itype(_Ptr<void>));
```

I think we need to deal with this better, but I'm not sure how we can. I think part of the problem is that we want to be able to pass both `_Array_ptr<T>` and `_Ptr<T>` to `free`, and converting between the two is not always viable. We also need `free(malloc(N))` to type-check, and same goes for calloc.

I don't know whether this is a bug where our definition of compatibility is not as transitive as it should be, or whether it's a more complex semantics issue.

**Comment by dtarditi** [comment]
This is fixed: we allow implicit conversions of _Array_ptr to _Ptr now.
