### ISSUE TITLE
Restrict implicit casts from pointers to generic type variables to void*

### ISSUE THREAD

**Issue by jp1729** [Microsoft/checkedc-clang#347]
Restrict implicit cast from pointers to generic type variables to void*. The purpose  of generic type variables is to not lose information about types. Implicit casts to void* defeats the purpose.

**Comment by dtarditi** [comment]
Wer're planning to restrict casts to and from void pointers in checked scopes (issue #571).  This seems like something that should be considered as part of implementing that.      For unchecked scopes, there doesn't seem to be a good reason to treat casts between void * and pointer to generic type variables diffrently than other pointer cats.  Closing this as redundant with issue #571.
