### ISSUE TITLE
Check that subexpressions of bounds expressions are non-modifying expressions.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#38]
Bounds expressions and where clauses can only use non-modifying expressions.   The checking for this needs to be implemented.

**Comment by dtarditi** [comment]
Sam added the method for determining whether an expression is non-modifying and used it to check the expression for the dynamic_check operator.   The method needs to be used to check the subexpressions of bounds expressions.

**Comment by lenary** [comment]
Closed by #129
