### ISSUE TITLE
Disallow casts to null-terminated pointers in checked scopes.

### ISSUE THREAD

**Issue by dtarditi** [microsoft/checkedc-clang#391]
We should not allow casts from unchecked, ptr, or array_ptr values to null-terminated in checked scopes.  Those pointers might not pointed to a null-terminated array, or the null terminator may be overwritten.

**Comment by dtarditi** [comment]
I believe we are already disallow implicit casts.  This work item is to disallow explicit casts.

**Comment by mgrang** [comment]
This was fixed in https://github.com/microsoft/checkedc-clang/pull/626 and tests were added in https://github.com/microsoft/checkedc/pull/367.
