### ISSUE TITLE
Infer widened bounds for pointers to null-terminated arrays

### ISSUE THREAD

**Issue by dtarditi** [microsoft/checkedc-clang#467]
Bounds can be widened when the element at the end of the bounds for a pointer to a null-terminated array is non-null.   This work item is to implement a dataflow analysis that determines widened bounds.

**Comment by mgrang** [comment]
This has been implemented in https://github.com/microsoft/checkedc-clang/commit/86b63d0b3014ab06edd7a5dbddc0687edb4fa4b8 and subsequent PRs.
