### ISSUE TITLE
Replace logic in NewTyp::mkTypForConstrainedType with a recursive AST visitor

### ISSUE THREAD

**Issue by awruef** [Microsoft/checkedc-clang#48]
The logic in `NewTyp::mkTypForConstrainedType` is ugly and probably wrong in some cases. It should be replaced with either a ginormous switch statement (which is more intuitive from an ML-persons point of view, but not LLVM idiomatic) or a `RecursiveASTVisitor` (which is ugly from an ML-persons point of view because functionality is smeared across a bunch of tiny functions, but is LLVM idiomatic).

**Comment by awruef** [comment]
The logic in `NewTyp::mkTypForConstrainedType` has been replaced with another class (`ConstraintVariable`) however, that infrastructure has a need for the same change.

**Comment by dtarditi** [comment]
We aren't likely to come back and do this for the rewriter.  Closing this issue.
