### ISSUE TITLE
Check bounds declarations after assignments to variables used in bounds declarations.

### ISSUE THREAD

**Issue by dtarditi** [microsoft/checkedc-clang#502]
An expression may assign to a variable used in a bounds declaration:
```
f(_Array_ptr<int> p : count(len), int len) {
   len = …;
}
```
We need to check that bounds declarations are still valid after assignment expressions that contain these assignments.

There are three parts to this work:
1. Determine when an expression assigns to a variable used in an in-scope bounds declaration.
2. For each expression statement, determine the set of bounds declarations that must be checked and facts relevant to checking (such as equality) that are true at the end of the statement.
3. Check that the bounds declarations are true using the relevant facts.

Analysis of facts in the presence of complicated intra-expression control-flow (#206) is beyond the scope of this work item.

**Comment by kkjeer** [comment]
This was implemented by #853.
