### ISSUE TITLE
Need automatic way to change header includes to checked versions

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc-clang#517]
When running checked-c-convert or otherwise doing translation for a number of source files, it would be really helpful if there were an automated tool or script to do this for the small number of *_checked headers in https://github.com/Microsoft/checkedc/tree/f464045e92f67c8ed144de475af6d9df653849a1/include

**Comment by AnnaKornfeldSimpson** [comment]
If the header file associated with that source file is also changed to <filename>.checked.h, replacing that in <filename>.checked.c would be great as well.

**Comment by dtarditi** [comment]
@AnnaKornfeldSimpson added a script to do this, so closing this issue.
