### ISSUE TITLE
checked-c-convert crashes with LLVM unreachable error

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc-clang#519]
checked-c-convert crashes with LLVM unreachable error when it detects a checked array type that it should be converting. If it doesn't hurt the analysis to continue, ignoring the checked array type, it would be nice to be able to convert a full program without crashing the tool.

**Comment by awruef** [comment]
Is there a stack backtrace, or file/line number, or output string, associated with the unreachable error? Or a test case?

**Comment by AnnaKornfeldSimpson** [comment]
Yes, it's hitting lines 98/99 in ProgramInfo.cpp

I don't have a good test case - I was trying to come up with contained test cases for the errors I found yesterday, which did not include this issue, and found this instead.

**Comment by awruef** [comment]
I see what the problem is, I can come up with a test case for this and fix it. Sorry about that.
