### ISSUE TITLE
checked-c-convert: some return types mangled

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [microsoft/checkedc-clang#520]
For a small number of functions `<return_type> * function_name…` gets replaced with `<return_type>function_name. No space between the type and the function name, and the * has just been swallowed.

Example: [parson.checked.c:126](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.checked.c#L126)
Original code: [parson.c:126](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.c#L126)
Error Produced: [talks about the itype on the return annotation](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/compilerErrors.txt#L4). The [accompanying warning](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/compilerErrors.txt#L1) is actually a little more specific as to the problem.

*To use this test case*:
- Clone https://github.com/AnnaKornfeldSimpson/parson
- Check out the *snapshotWeUse* branch
- `make test` to build the original code. `make testchecked` to build with the copies produced by checked-c-convert.
- `convert.sh` runs checked-c-convert on the original code and outputs to  `*checked*` files. If you re-run it, also *edit parson.checked.c to use parson.checked.h*. convert.sh may need modifications to run in Windows.
- Compiler errors can be compared with `compilerErrors.txt` (produced on a Ubuntu system, not sure if it will perfectly match in Windows)

**Comment by awruef** [comment]
Note to myself, I bet this is related to #524.

**Comment by dtarditi** [comment]
The convert tool has been mostly rewritten (see PR #642).  Please reopen this issue if it still exists.
