### ISSUE TITLE
Checked-c-convert: function return values converted, but caller assigns it to variable of old type

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [microsoft/checkedc-clang#523]
If a function return value is converted from <T>* to _Ptr<T>, callers of that function must be aware of that change and either cast the return value back or change the type of the variable to which they are assigning the return value. If that does not happen there will be an incompatible types error.

Example: [parson.checked.c:360](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.checked.c#L360)
The converted function is declared at: [parson.checked.c:94](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.checked.c#L94)
Original code: [parson.c:360](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.c#L360)
Original function declaration: [parson.c:94](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.c#L94)
Error Produced: [assigning to <leftside_type> from incompatible type <converted return value>](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/compilerErrors.txt#L28).

*To use this test case*:
- Clone https://github.com/AnnaKornfeldSimpson/parson
- Check out the *snapshotWeUse* branch
- `make test` to build the original code. `make testchecked` to build with the copies produced by checked-c-convert.
- `convert.sh` runs checked-c-convert on the original code and outputs to  `*checked*` files. If you re-run it, also *edit parson.checked.c to use parson.checked.h*. convert.sh may need modifications to run in Windows.
- Compiler errors can be compared with `compilerErrors.txt` (produced on a Ubuntu system, not sure if it will perfectly match in Windows)

**Comment by dtarditi** [comment]
The convert tool has been mostly rewritten (see PR #642).  Please reopen this issue if it still exists.
