### ISSUE TITLE
Checked-c-convert: Static modifier removed from function declaration when return value converted

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [microsoft/checkedc-clang#524]
Static modifiers preceding the return type of a function are removed from the declaration when the return type is converted from <T>* to _Ptr<T>.

Example: [parson.checked.c:94](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.checked.c#L94)
Original code: [parson.c:94](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.c#L94)
I have not yet seen a specific error message for this yet; I just noticed while comparing sources.

*To use this test case*:
- Clone https://github.com/AnnaKornfeldSimpson/parson
- Check out the *snapshotWeUse* branch
- `make test` to build the original code. `make testchecked` to build with the copies produced by checked-c-convert.
- `convert.sh` runs checked-c-convert on the original code and outputs to  `*checked*` files. If you re-run it, also *edit parson.checked.c to use parson.checked.h*. convert.sh may need modifications to run in Windows.
- Compiler errors can be compared with `compilerErrors.txt` (produced on a Ubuntu system, not sure if it will perfectly match in Windows)

**Comment by AnnaKornfeldSimpson** [comment]
I'm not sure I know precisely all the implications of `static` on a function in c.
@dtarditi Is this a correctness issue or more stylistic?

**Comment by dtarditi** [comment]
@AnnaKornfeldSimpson, it could cause name collisions.  A static function is local to the C file being compiled.  If the static modifier is dropped, the function becomes globally scoped.  This could cause a name collision if two separate files defined the same static function.

**Comment by dtarditi** [comment]
The convert tool has been mostly rewritten (see PR #642).  Please reopen this issue if it still exists.
