### ISSUE TITLE
Compiler Crash "Assertion !AS->hasBoundsExpr() failed"

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc-clang#526]
I made a change that I was certain was incorrect, but I wanted to see what guidance I would get from the error message. Instead, it seems to have been sufficiently unpredictable as to crash the compiler. 
It prints the error message including `Assertion !AS->hasBoundsExpr() failed` then pauses for several seconds before printing the stack trace.

Attached are the information printed in the terminal window, and files specified in the bug report instructions (remove extra ".txt" extension after downloading).
[clangCrashTerminalOutput.txt](https://github.com/Microsoft/checkedc-clang/files/2189432/clangCrashTerminalOutput.txt)
[parson-3e2b4f.c.txt](https://github.com/Microsoft/checkedc-clang/files/2189442/parson-3e2b4f.c.txt)
[parson-3e2b4f.sh.txt](https://github.com/Microsoft/checkedc-clang/files/2189443/parson-3e2b4f.sh.txt)
[tests-c3dc85.c.txt](https://github.com/Microsoft/checkedc-clang/files/2189444/tests-c3dc85.c.txt)

**Comment by dtarditi** [comment]
Yes, this is a compiler bug.    The following small piece of code will trigger this crash:
```
struct obj {
  _Array_ptr<_Nt_array_ptr<char>> names : count(num);
  size_t num;
};

void f(const struct obj *object ) {
   size_t i = 0;
   _Nt_array_ptr<const char> t : count(0) = _Dynamic_bounds_cast<_Nt_array_ptr<const char>>(object->names[i], count(0));}
```
It looks like we are accidentally walking a bounds expression that the compiler has inferred to use when implementing the dynamic check.   We end up traversing the IR for the expression object->names[I] twice, which triggers the assert.
