### ISSUE TITLE
Checked-c-convert: function parameter renamed

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [microsoft/checkedc-clang#528]
Several function parameters named "ix" are renamed to "i" by checked-c-convert, but just in the parameter list, not in the function body. This means there's no declaration for the uses of "ix" in the function body and no use of the renamed parameter "i".

Example: [parson.checked.c:1542](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.checked.c#L1542)
Original code: [parson.c:1542](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/parson.c#L1542)
Error Produced: [use of undeclared identifier 'ix'](https://github.com/AnnaKornfeldSimpson/parson/blob/snapshotWeUse/compilerErrors.txt#L238). There is also a warning for unused parameter 'i'

*To use this test case*:
- Clone https://github.com/AnnaKornfeldSimpson/parson
- Check out the *snapshotWeUse* branch
- `make test` to build the original code. `make testchecked` to build with the copies produced by checked-c-convert.
- `convert.sh` runs checked-c-convert on the original code and outputs to  `*checked*` files. If you re-run it, also *edit parson.checked.c to use parson.checked.h*. convert.sh may need modifications to run in Windows.
- Compiler errors can be compared with `compilerErrors.txt` (produced on a Ubuntu system, not sure if it will perfectly match in Windows)

**Comment by awruef** [comment]
I have a suspicion that I fixed this in a previous PR without knowing, I tried to reproduce now and it did the right thing. I'll investigate more.

**Comment by dtarditi** [comment]
The convert tool has been mostly rewritten (see PR #642).  Please reopen this issue if it still exists.
