### ISSUE TITLE
checked-c-convert: itype(void* ) instead of conversion to checked type

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [microsoft/checkedc-clang#550]
Some odd itype behavior when running checked-c-convert on some memory functions, here's a short repro:

```
#include <string_checked.h>
void MemoryCopy(void* dest, const void* src, int sSize) {
    if (dest != NULL && src != NULL)
    {
        memmove(dest, src, sSize);
    }
}
```

Expected conversion (given the definition of memmove):
` void MemoryCopy(void *dest : byte_count(sSize), const void *src : byte_count(sSize) , int sSize) `

What I saw:
`void MemoryCopy(void *dest : itype(void* ), const void *src : itype(_Ptr<const void>), int sSize)`

Both itypes are wrong, since memmove requires a byte_count and so cannot be _Ptr type, but the one for dest is especially confused.

**Comment by dtarditi** [comment]
The convert tool has been mostly rewritten (see PR #642).  Please reopen this issue if it still exists.
