### ISSUE TITLE
checked-c-convert: Line endings and comments clobbered during conversion

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [microsoft/checkedc-clang#551]
This isn't a correctness issue, but it makes debugging correctness issues a bit more difficult.

Original code:
```
UINT32
foo(
    UINT32           cmdCode,       // IN: Command code
    BYTE            *cmdBuffer,     // OUT: Command buffer 
    INT32            bufCapacity    // IN: Capacity of 'cmdBuffer' in bytes
);
```
After conversion:
` UINT32 foo(UINT32 cmdCode, BYTE *cmdBuffer : itype(_Ptr<BYTE> ) , INT32 bufCapacity);`

When looking at the comments, it's pretty clear that the conversion here is not correct, but without the comments it's much more difficult to see.

**Comment by dtarditi** [comment]
The convert tool has been mostly rewritten (see PR #642).  Please reopen this issue if it still exists.
