### ISSUE TITLE
Function pointers to generic functions with bounds-safe interfaces

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc-clang#553]
Unexpected complexity for generic functions! Some people want to define their own memory management functions. To do this, they'll be defining a function pointer to a malloc-like function. For example:
```
typedef void * my_malloc_fun(size_t s) : byte_count(s) itype(_Array_ptr<void>);
typedef _Ptr<my_malloc_fun> Use_This_Malloc_Fun;
``` 
in the header and then
`static Use_This_Malloc_Fun x_malloc = &malloc;`
in the code file.  Produces an error about how the `&malloc` needs type arguments, which doesn't make a lot of sense since it isn't being called here.
The most natural place to mark the generic-ness is at the lowest level:
`typedef _Itype_for_any(T) void * my_malloc_fun(size_t s) : byte_count(s) itype(_Array_ptr<T>);`
and then call `x_malloc<concrete_type>` as one would with malloc.
However, this does not address the complaint about &malloc needing type arguments.

**Comment by dtarditi** [comment]
This is fixed.   We still need to handle taking the address of a generic function applied to type variables.  That is tracked by issue #559.
