### ISSUE TITLE
memcpy used to transform uint8_t* to uint32_t*

### ISSUE THREAD

**Issue by AnnaKornfeldSimpson** [Microsoft/checkedc-clang#579]
Definitely a question rather than a bug: 
I'm running into code that uses memcpy to transform quartets of (unsigned) bytes into unsigned 32-bit ints. This is a problem since `memcpy<type>` expects `type` to be the same for src and dest. Is there a recommended idiom for this? e.g. dynamic bounds casting one of the arguments...

Thanks!

**Comment by dtarditi** [comment]
You could use `memcpy<void>` in this case.  That would cause the code to behave like it used to.

At some point, we plan to restrict casts to void pointers in checked scopes to avoid "type confusion" errors (issue #571).  However, this only seems to be necessary for pointers to data containing pointers.  It isn't clear we should restrict casts between pointers to void and pointers to integer:  every sequence of bits is a valid integer.

**Comment by AnnaKornfeldSimpson** [comment]
Thanks!
