### ISSUE TITLE
Take the LUB of constraints when multiple constraints exist and they might differ

### ISSUE THREAD

**Issue by awruef** [microsoft/checkedc-clang#59]
In `FunctionVariableConstraint::mkString` we take the first constraint in a set for the return and parameters and use them. Right now this should be okay because they should all be constrained to be equal, so whatever one is resolved to should be the same as the others. However, maybe in the future that won't be true, so we should instead be more generic and take the LUB of all the `ConstraintVariables` in the set.

**Comment by dtarditi** [comment]
This work item is stale, so closing it.  The convert tool has been mostly rewritten (see PR #642).
