### ISSUE TITLE
Issues with PATH when installing via Windows binary

### ISSUE THREAD

**Issue by srajg** [Microsoft/checkedc-clang#600]
Hi, I am a student at the University of Maryland and I will be assisting Dr. Hicks with some research on CheckedC. I'm trying to install CheckedC on my Windows machine by following the instructions on https://github.com/Microsoft/checkedc-clang/releases. I am using the x64 binaries. 

During installation, I have the option to add LLVM to PATH or not. I tried installing by selecting that option but got an error saying "PATH too long installer unable to modify PATH". I tried uninstalling and reinstalling without trying to modify PATH, but then manually adding a new environment variable (Windows Settings > Edit the system environment variables) with the name "clang" and value "C:\Program Files\CheckedC-LLVM\bin".

Regardless, "clang" is not a recognized command on Cygwin or Git bash or Command Prompt, and I'm unable to compile a C file using the CheckedC compiler. Any suggestions? Thanks in advance.

**Comment by dtarditi** [comment]
There a 4Kbyte limit on the length of the PATH environment variable on Windows.   This can happen when you install too many software packages that add directories to the path, or you install the software in directories that  are deeply nested  

You'll need to shorten the current contents of the PATH variable.  The easiest way to solve this is to delete some other unused software package from your path.  Also make sure that your install directory is something with a relatively short name.

As a short-term work around, you can just go to a command-line and manually set your PATH variable to only include the Checked C LLVM binary directory
```
set PATH=C:\Program Files\CheckedC-LLVM\bin
```
You could also invoke the clang compiler directly:
```
set clang=C:\Program Files\CheckedC-LLVM\bin\clang.exe
%clang% ...
```

**Comment by srajg** [comment]
That fixed it, thanks so much!
