### ISSUE TITLE
Implicit bounds are not respected for `itype(_Array_ptr)`

### ISSUE THREAD

**Issue by Machiry** [microsoft/checkedc-clang#615]
# Problem:
In the following program:
```
#include <string_checked.h>
#include <stdlib_checked.h>
#include <stdchecked.h>

int main(int argc, nt_array_ptr<char> argv checked[] : count(argc)) {
    array_ptr<char> dummy : count(argc) = malloc(argc);
    array_ptr<char> dummy2 = dummy;
    free(dummy2);
}
```
The bounds for `dummy2` are expected to be implicitly derived from the assignment i.e., `dummy2 = dummy`. Thus, the `free` call should be fine. However, type checker throws the following error:
```
9:10: error: argument has unknown bounds, bounds expected because the 1st parameter has bounds
    free(dummy2);
         ^~~~~~
```

However, if I call `free(dummy)`, everything works fine as the bounds of `dummy` are explicitly declared.

The signature for `free` is:
```
_Itype_for_any(T) void free(void *pointer : itype(_Array_ptr<T>) byte_count(0));
```
Where it expects an `itype` array pointer. My understanding is that `dummy2` inherits bounds from `dummy` and thus should be a valid `array_ptr`. Correct me If I am missing something here.

**Comment by dtarditi** [comment]
No, Checked C doesn't propagate bounds implicitly.   In the declaration of `dummy2`,  `array_ptr<char> dummy2` is interpreted as having bounds of `bounds(unknown)`.
