### ISSUE TITLE
Issue converting typedef pointers to checked types

### ISSUE THREAD

**Issue by hasantouma** [microsoft/checkedc-clang#619]
I came across this issue when converting the [icecast](http://icecast.org/) code.

The issue can be illustrated with this small example:

```
#ifndef foo
#define foo int
#endif

int main() {
  foo* a;

  return 0;
}
```

`checked-c-convert` produces this:

```
#ifndef foo
#define foo int
#endif

int main() {
  _Ptr<int>  aa;

  return 0;
}
```

Note the variable name change and the `_Ptr<>` change from `foo` to `int`

**Comment by hasantouma** [comment]
This is a more extensive example of the issue:

C code:
```
#ifndef foo
#define foo int
#endif

int main() {
  foo *a, *b, *c;

  return 0;
}
```

`checked-c-convert` output:
```
#ifndef foo
#define foo int
#endif

int main() {
  foo *a, *b, *c_Ptr<int> a;
_Ptr<int> b;
_Ptr<int> c;
;

  return 0;
}
```

**Comment by mgrang** [comment]
Transferred this issue to the 3C team: https://github.com/correctcomputation/checkedc-clang/issues/409
