### ISSUE TITLE
Using where clause

### ISSUE THREAD

**Issue by Machiry** [microsoft/checkedc-clang#627]
I am trying to use the `where` clause as shown in the specification, Page 40
```
#include <stdchecked.h>
#pragma CHECKED_SCOPE ON
int sum(array_ptr<int> start : bounds(start, end), array_ptr<int> end) {
      end = end - 1 where start : bounds(start, end + 1); 
      return 1;  
}

int main(int argc, nt_array_ptr<char> argv checked[] : count(argc)) {
}
```

However, I get the following error when I try to compile:
```
where_nt.c:4:20: error: expected ';' after expression
      end = end - 1 where start : bounds(start, end + 1);
                   ^
                   ;
where_nt.c:4:21: error: expected expression
      end = end - 1 where start : bounds(start, end + 1);
                    ^
/Users/machiry/Projects/checkedc/llvm-stuff/checkedc-build/lib/clang/8.0.0/include/stdchecked.h:11:15: note: expanded from macro 'where'
#define where _Where
              ^
2 errors generated.
```
Am I missing something here? Any help is greatly appreciated.

**Comment by dtarditi** [comment]
This is not implemented yet by design.   We've divided the Checked C extension into a V1 set of features and post-V1 set of features.  Where clauses are in the post-V1 subset: https://github.com/microsoft/checkedc-clang/wiki/Implementation-roadmap-and-status.

**Comment by Machiry** [comment]
Ah okay. I thought so, but the `#define` in the `stdchecked.h` tricked me.
