### ISSUE TITLE
Bug(s) in parsing generic function calling another generic function with argument.

### ISSUE THREAD

**Issue by jzhou76** [microsoft/checkedc-clang#641]
The following code crashes the compiler:

```C
for_any(T) void foo(ptr<T> p) {}

for_any(T) void bar(ptr<T> p) {
    foo<T>(p)
}
```

The compiler throws error message
```
1.	./libchecked.h:47:9: current parser token '('
2.	./libchecked.h:43:31: parsing function body 'bar'
3.	./libchecked.h:43:31: in compound statement ('{}')
```

The attached file [crash_log.txt](https://github.com/microsoft/checkedc-clang/files/3429621/crash_log.txt) is the complete crash log collected by compiling the code above on a Ubuntu 18.04. The compiler is the same as commit https://github.com/microsoft/checkedc-clang/commit/2cc6b466eb96f3ae078f6de66fc3aeec22261ca5.

**Comment by dtarditi** [comment]
This no longer crashes the compiler.
