### ISSUE TITLE
Parameter subtyping for nested pointers

### ISSUE THREAD

**Issue by hasantouma** [microsoft/checkedc-clang#676]
The following code follows the subtyping relationship.

Note that `nt_arr` can be passed to functions that expect `_Ptr<char>` and `_Array_ptr<char>` (`foo()` and `bar()`, respectively) but `nt_nt_arr` can't be passed to a function that expects a nested pointer of `_Array_ptr<_Ptr<char>>`

`ex.c`:
```
#include <stdlib_checked.h>

void foo(_Ptr<char> x);

void bar(_Array_ptr<char> y);

void baz(_Array_ptr<_Ptr<char>> z);

int main(void) {

  int len;
  _Nt_array_ptr<char> nt_arr : count(len) = NULL;
  _Nt_array_ptr<_Nt_array_ptr<char>> nt_nt_arr : count(len) = NULL;

  foo(nt_arr);
  bar(nt_arr);
  baz(nt_nt_arr); // Error!

  return 0;
}
```
Running Checked C clang:
```
~$ cclang -c ex.c
ex.c:18:7: error: passing '_Nt_array_ptr<_Nt_array_ptr<char>>' to parameter
      of incompatible type '_Array_ptr<_Ptr<char>>'
  baz(nt_nt_arr); // Error!
      ^~~~~~~~~
ex.c:8:33: note: passing argument to parameter 'z' here
void baz(_Array_ptr<_Ptr<char>> z);
                                ^
1 error generated.
```

**Comment by dtarditi** [comment]
This is not a bug.  If we allowed the call to `baz`, `baz` could overwrite the inner pointer with a _Ptr.  This is not an _Nt_array_ptr, so it would break the invariants around  _Nt_array_ptr.  Consider:
```
static char c = 0;
static _Ptr<char> = &c;
void baz(_Array_ptr<_Ptr<char>> z : count(len), int len) {
   *z  = c;
}
```

**Comment by Machiry** [comment]
This is a valid point. We were using the function subtyping (covariant and contravariant) for the entire type but it is safe only to use it on the outer type.

**Comment by hasantouma** [comment]
@Machiry Then we should make note to change our tool. I'll close this issue and open one in our fork so we can remove it from the tool.
