### ISSUE TITLE
itype with bounds

### ISSUE THREAD

**Issue by hasantouma** [microsoft/checkedc-clang#677]
It's unclear why parameters with itypes don't allow for bounds to be declared inside the itype. I wrote a small example to explain why I'm confused.

`foo()` and `bar()` take in the same type, except that `bar()` can also be called from `_Unchecked` scopes with `int *` rather than just `_Array_ptr<int>`. Why can't I declare the bounds of `x` for the function `bar()`?

`foo.c`:
```
#include <stdlib_checked.h>

int foo(_Array_ptr<int> x : count(len), int len);

int bar(int *x : itype(_Array_ptr<int> : count(len)), int len);

int main(void) {

  int len = 5;
  _Array_ptr<int> x : count(len) = NULL;
  foo(x, len);
  bar(x, len);

  return 0;
}
```

Running this code will produce the following error:
```
$ cclang -c foo.c
foo.c:6:40: error: expected ')'
int bar(int *x : itype(_Array_ptr<int> : count(len)), int len);
                                       ^
foo.c:6:23: note: to match this '('
int bar(int *x : itype(_Array_ptr<int> : count(len)), int len);
                      ^
1 error generated.
```

**Comment by dtarditi** [comment]
The correct syntax is to have a separate bounds expression:

int bar(int *x : itype(_Array_ptr<int>) count(len), int len);

A variable declarator can be followed by a ':', an optional itype expression, and an optional bounds expression.  At least one of the itype or bounds expression must appear after the ':'

**Comment by dtarditi** [comment]
@hasantouma, please reopen this if you have additional questions.
