### ISSUE TITLE
declare multi-dimensional arrays of fixed length

### ISSUE THREAD

**Issue by hasantouma** [microsoft/checkedc-clang#678]
How do I declare the bounds of a multi-dimensional array?

Suppose I have the following C code:

```
void foo(int **x, int row, int col) {

  int i, j;
  for (i = 0; i < row; i++) {
    for (j = 0; j < col; j++) {
      x[i][j] = i + j;
    }
  }

}

int main(void) {

  int row = 5;
  int col = 3;
  int **x;
  foo(x, row, col);

  return 0;
}
```

If I want to convert it to Checked C, I would rewrite it like this:
```
#include <stdlib_checked.h>

void foo(_Array_ptr<_Array_ptr<int>> x : count(row), int row, int col) {

  int i, j;
  for (i = 0; i < row; i++) {
    for (j = 0; j < col; j++) {
      x[i][j] = i + j;
    }
  }

}

int main(void) {

  int row = 5;
  int col = 3;
  _Array_ptr<_Array_ptr<int>> x : count(row) = NULL;
  foo(x, row, col);

  return 0;
}
```

But this produces the following error:
```
multi_dim_arrays.c:9:7: error: expression has unknown bounds
      x[i][j] = i + j;
      ^~~~~~~
1 error generated.
```

Intuitively, I would want to do something like this:
```
_Array_ptr<_Array_ptr<int> : count(col)> x : count(row) = NULL;
```
But that produces even more errors.

**Comment by dtarditi** [comment]
In C, this is not considered a multi-dimensional array.   A multi-dimensional array has type `array of array of T` and so on.   You have might be called in Java a "ragged array": an array of arrays, where each inner array could potentially have a different length.

In general, Checked C cannot represent bounds in inner pointers at this type: given `_Array_ptr<Array_ptr<int>>, we cannot represent the bounds on the innermost pointer.   This has to do with issues around pointer aliasing.   If you want to represent this, you'll need to use a struct that pairs the pointer with a length.

You could introduce a struct of this form:
```
struct InnerPtr {
     _Array_ptr<int> p : count(len);
     int len;
}
```

You could then retype this as 
```
InnerPtr *;
```
There is a proposal to allow the inner-most pointer to have constant length: https://github.com/microsoft/checkedc/issues/296.   However, this still won't support what you want, what is a variable-sized length on the innermost pointer.
