### ISSUE TITLE
Is casting to `_Ptr` type allowed?

### ISSUE THREAD

**Issue by Machiry** [microsoft/checkedc-clang#682]
Issue type: Question

Will casting to `Ptr` type be ever allowed?

Example:

```
  void foo(_Ptr<int> pi) {
   ...
  }

  bar(void *x) {
   ...
  int *y = (int *)x;
  foo((_Ptr<int>)y);
  ...
 }
```

As of now, this is not allowed. checkedc-clang expects bounds and throws the following error:

```
expression has unknown bounds, cast to ptr<T> expects source to have bounds
```

Will this ever be supported? If not, what is the alternative of converting non-checked pointers to checked ones, especially in the cases of the partially converted codebase.

**Comment by dtarditi** [comment]
You can use _Assume_bounds_cast to do the casting in this case.   The issue is that y has no bounds.  At the cast site, there is no reason  to believe that y actually points to an integer.

**Comment by dtarditi** [comment]
To answer the question posed in the title of the issue, yes, casts to _Ptr<T> are allowed.  The bounds of the source pointer must allow access to memory that is at least the size of T.

**Comment by Machiry** [comment]
Thank you!
