### ISSUE TITLE
Bounds-aware checker in clang static analyzer for unchecked functions

### ISSUE THREAD

**Issue by saeednj** [microsoft/checkedc-clang#734]
To check that unchecked functions with bounds-safe interface, do not access memory out of the declared bounds, we can write/extend a clang static analyzer checker. This checker needs to know about the bounds information that Checked-C provides, and use these bounds to do the out-of-bounds access check. However, commonly the bounds are defined over arguments of the function (e.g. `int *a : count(n), int n`). The symbolic engine of clang static analyzer and its internal solver, cannot handle evaluating expressions that don't have a concrete starting point. Therefore, analyzing only a function definition is not feasible with the current static analyzer. We can improve the solving ability of the internal solver by querying a theorem prover (like Z3) on complex index and bounds expression.

The desired abilities would be:
1. Read and use bounds-safe information of a function
2. Use Z3 to handle complex expressions

**Comment by sulekhark** [comment]
Closing this issue as the implementation work on this is completed. Any future work on this can create new issues if required.
