### ISSUE TITLE
Verification of memory accesses in unchecked functions against bounds-safe information

### ISSUE THREAD

**Issue by saeednj** [microsoft/checkedc-clang#735]
Claiming any memory safety guarantee for a mix of checked and unchecked codes is a challenge, because there is no bounds checking in the unchecked codes and bounds information might be lost when the data flows through unchecked regions.

The goal is to verify whether the unchecked functions violate their bounds-safe interfaces. We can treat bounds-safe information as partial specification and generate verification conditions out of dynamic checks, then pass the code with the assumptions and assertions to a software model checker for safety checking of the memory accesses.

**Comment by sulekhark** [comment]
Closing this issue as the implementation work on this is merged. For any future work on this implementation, new issues can be opened.
