### ISSUE TITLE
Constraint library should deal with conflicts

### ISSUE THREAD

**Issue by awruef** [Microsoft/checkedc-clang#87]
A conflict could arise in a situation where a functions bounds-safe interface specifies `_Ptr<T>` for something in an interface, but our analysis determines that it can't be a `_Ptr`. In that situation, we have some Checked C tools at our disposal to deal with the problem (like casts) but the constraint library can't deal with this situation at all. 

The constraint library should be modified so that:

 - Constraints that "hold a value down" are possible (i.e. `q_i != ARR /\ q_i != WILD`)
 - Conflicting constraints are identified and reported as solve failures 

Once that's done, the client of the constraint library can start to implement solutions to conflicts discovered around external specifications.

**Comment by dtarditi** [comment]
I think this is subsumed by more recent work.
