### ISSUE TITLE
Functions w/out prototypes can't be used in checked scopes?

### ISSUE THREAD

**Issue by aaronjeline** [microsoft/checkedc-clang#882]
`````c
void foo() _Checked { return; }
void bar() _Checked { foo(); }
``````
Fails to compile with: `error: function without a prototype cannot be used or declared in a checked scope
`

**Comment by mgrang** [comment]
This is similar to https://github.com/microsoft/checkedc-clang/issues/883. This is by design. See explanation in https://github.com/microsoft/checkedc-clang/issues/883.
