### ISSUE TITLE
Compilation error when returning a struct from nullary function

### ISSUE THREAD

**Issue by sroy4899** [microsoft/checkedc-clang#883]
Consider the following code: 
```
struct foo { 
    _Ptr<int> x;
};

_Ptr<struct foo> fooPtr(void) { 
    return 0;
}

struct foo fooFunc() { 
    _Ptr<struct foo> returned =  fooPtr(); 
    return *returned;
}
```
This results in a compilation error: 
```
error: function with no prototype cannot have a return type that is a structure with a member with a checked type
struct foo fooFunc() { 
``` 
Since I'm not indicating `fooFunc` as a checked region, it's not clear to me why I am unable to return the struct from the function. 

Note: If I change `fooFunc` to a function with parameters, or even change its signature to read `struct foo fooFunc(void)`, the program compiles without incident.

**Comment by mgrang** [comment]
This is by design. In Checked C, no prototype functions cannot return checked types. See Section 5.5 of the Checked C language extension specification.

```
We define the set of types E that are an error to use with functions without prototypes by induction. It includes:
1. Checked pointer and array types.
2. Complete structure and union types with members that have types in E.
...

We define the following rules for unchecked scopes:
1. It is an error to call a function that is declared to have no prototype and pass or return a
value whose type is in E.
```

**Comment by sroy4899** [comment]
Thank you for your explanation. One concern of mine though is that if I were to change the signature of the function `fooFunc` s.t. the program looked like this instead: 
```
struct foo { 
    _Ptr<int> x;
};

_Ptr<struct foo> fooPtr(void) { 
    return 0;
}

struct foo fooFunc(int y) { 
    _Ptr<struct foo> returned =  fooPtr(); 
    return *returned;
}
```
the compiler does not complain. Unless I'm misunderstanding what you mean by a non-prototype function, `fooFunc` doesn't have a prototype, and yet the code compiles. Similarly, if instead of `int y` I put `void` it would also compile. Is this because I'm misunderstanding what a prototyped function is?

**Comment by dopelsunce** [comment]
@sroy4899 To answer your question about prototypes:

The function `fooFunc()` with zero parameters does not define a prototype in C. The empty parentheses roughly mean "the argument list is undefined" and the declaration is essentially a placeholder that does not define the parameter types. To make it a prototype you have to add types to the parameters, such as putting `void` or `int y` in the parentheses. 

Note this is different in (modern) C++, where an empty parameter lists `()` is equivalent to `(void)`.

**Comment by mgrang** [comment]
To add to @dopelsunce 's response, refer the C11 spec section 6.2.1:
`A function prototype is a declaration of a function that declares the types of its parameters.`
