### ISSUE TITLE
Runtime failure with using global variable in bounds

### ISSUE THREAD

**Issue by mgrang** [microsoft/checkedc-clang#884]
If the bounds of a variable are declared using a global variable then it becomes difficult to reason about the bounds because any function could change the value of the global thus invalidating the bounds. In such cases, we should declare a local variable inside the function and assign it the global variable's value and use this local variable in the bounds. But doing so currently causes a runtime failure.

Refer https://github.com/microsoft/checkedc-llvm-test-suite/commit/7feb393d84c770ed5489e4b4f7c2245be74704f2
Here, the bounds of `tmpPerScc` are declared using the global variable `totalSCC`. We have declared a local variable `originalTotalSCC` but using this local in the bounds causes a runtime failure:

`_Array_ptr<ulong> perSCC : count(originalTotalSCC + 1) = tmpPerSCC; //runtime failure`

**Comment by sulekhark** [comment]
Fixed. Refer microsoft/checkedc-llvm-test-suite@7feb393.
