### ISSUE TITLE
Assignments within conditional expressions should kill widened bounds

### ISSUE THREAD

**Issue by kkjeer** [microsoft/checkedc-clang#895]
Expressions within a conditional operator that modify variables used in a widened bounds expression currently do not kill the widened bounds. For example,

```
void f(nt_array_ptr<char> p : count(i), unsigned i, int flag) {
  if (*(p + i)) {
    // The i++ expression should kill the widened bounds of p.
    flag ? i++ : i;
  }
}
```

**Comment by mgrang** [comment]
Fixed in https://github.com/microsoft/checkedc-clang/pull/898

**Comment by mgrang** [comment]
@kkjeer Could you please verify if the above PR fixes the issue?
