### ISSUE TITLE
Bounds safe interface not recognized on function return type

### ISSUE THREAD

**Issue by jackastner** [microsoft/checkedc-clang#918]
It looks like bounds safe interfaces on functions return types are not being parsed correctly. Given a function declaration like `int *test() : itype(_Ptr<int>));` the `FunctionDecl` object I get returns `nullptr` for `getInteropTypeExpr()`.

Trying to compile this code should demonstrate the problem. 

```c
int * test() : itype(_Ptr<int>) {
  return 0;
}

void foo() _Checked {
  _Ptr<int> a = test();
}
```

compiled with `clang -c error.c` gives an error. 

```
error.c:6:17: error: return used in a checked scope must have a checked type or a bounds-safe interface
  _Ptr<int> a = test();
                ^
error.c:1:1: note: return declared here
int * test() : itype(_Ptr<int>) {
^
1 error generated.
```

tested with

```
clang version 9.0.0 (/home/cc/checkedc-clang/clang 50f764a5fdcb77e30e9b653a81cb83f2be35498a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/cc/checkedc-clang/llvm/build/bin
```

**Comment by mgrang** [comment]
In C, the correct way to declare a function which takes no parameters is:
`T f(void)`

In C, declaring a function as `T f()` means that the function takes an unknown number of parameters.

Refer section 6.7.6.3 point no. 10 of the C11 spec: http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1570.pdf

So upon correctly declaring the function `test` as follows you should no longer see the error:
`int * test(void) : itype(_Ptr<int>) {
  return 0;
}`

**Comment by mgrang** [comment]
On the other hand, the error message itself should be fixed to say something like "Invalid function prototype" so that the error is more clear to the user. I have filed an issue to track this: https://github.com/microsoft/checkedc-clang/issues/921
