### ISSUE TITLE
Problem with manually running tests on Windows X86

### ISSUE THREAD

**Issue by mattmccutchen-cci** [microsoft/checkedc-clang#963]
According to @mgrang, there is [a problem that makes manually running the tests on Windows X86 difficult](https://github.com/microsoft/checkedc-clang/pull/956#issuecomment-752272736).  I'm filing an issue to have something to link to for this problem; @mgrang, please feel free to edit the title and description to make them more informative.

Until this problem is fixed, the 3C team won't be responsible for testing of 3C on Windows X86; instead, any 3C tests that fail on Windows X86 will be marked unsupported.  See #961, for example.

**Comment by mgrang** [comment]
https://github.com/microsoft/checkedc-automation/pull/22 switches the x86 build of checkedc-clang to use x64 MSVC.

**Comment by mattmccutchen-cci** [comment]
If you think this should work now, we'll go ahead and try it.  We're using Visual Studio per the [instructions](https://github.com/microsoft/checkedc-clang/blob/master/clang/docs/checkedc/Setup-and-Build.md#visual-studio), so I'll just try choosing the `msvc_x86_x64` toolset there as instructed.  Maybe we should adopt more of your automation, though it would be great if we could still use Visual Studio in combination with it for interactive development and debugging.

**Comment by sulekhark** [comment]
@mattmccutchen-cci  You can go ahead and try it. With this change, three checkedc test cases are failing for us in a trial build/test on our build machine. We are looking into those.

**Comment by mgrang** [comment]
PR https://github.com/microsoft/checkedc-automation/pull/22 is merged.
