### ISSUE TITLE
Fix compiler warnings in clang build.

### ISSUE THREAD

**Issue by dtarditi** [Microsoft/checkedc-clang#97]
I'm building the Checked C version of clang on Linux and seeing some compiler warnings about ignored qualifiers in Type.h (line 3357).  There are additional warnings about unhandled switch cases.  We should fix these warnings.

**Comment by awruef** [comment]
I've seen these too, I think that the unhandled switch cases are related to stuff added by Checked C, the names of the unhandled cases seemed to be names of Checked C classes added to clang.

**Comment by dtarditi** [comment]
This is fixed.
